# import sys
# from exception import customException
# import logging
# import logger

# if __name__ == "__main__":
#     try:
#         a = 1/0
#     except Exception as e:
#         logging.info("ZeroDivisionError!!! from Utils")
#         raise customException(e, sys)